name: Validate ADRs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/decisions/**'
      - 'examples/**'
      - 'src/**'
      - 'schemas/**'
      - 'action.yml'
  pull_request:
    paths:
      - 'docs/decisions/**'
      - 'examples/**'
      - 'src/**'
      - 'schemas/**'
      - 'action.yml'

jobs:
  validate-project-adrs:
    name: Validate Project ADRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate project ADRs
        # zircote/structured-madr@v1.1.0
        uses: zircote/structured-madr@427992745ad30e973289c6025f101181d968e50a
        with:
          path: docs/decisions
          strict: 'false'

  validate-examples:
    name: Validate Example ADRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate example ADRs
        # zircote/structured-madr@v1.1.0
        uses: zircote/structured-madr@427992745ad30e973289c6025f101181d968e50a
        with:
          path: examples
          strict: 'false'
